name: "custom shell"

on:
  workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '.github/workflows/shell.yml'

      - name: Display executed script file name
        shell: bash
        run: echo "$0"

      # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#custom-shell
      - name: Display the environment variables and their values
        shell: perl {0}
        run: |
          print %ENV

      - name: default install Node.js version
        run: node --version

      - name: Run with Node.js
        shell: node {0}
        run: |
          console.log(process.env);

      - name: Run zx
        shell: npx zx@8.1.8 {0}
        run: |
          const branch = await $`git branch --show-current`
          echo`Current branch is ${branch}.`
