name: "custom shell"

on:
  workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        shell: bash
        run: echo $PATH

      # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#custom-shell
      - name: Display the environment variables and their values
        shell: perl {0}
        run: |
          print %ENV
